apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-flyway-outside
  namespace: flyway
  labels:
    app: spring-flyway-outside
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-flyway-outside
  template:
    metadata:
      labels:
        app: spring-flyway-outside
    spec:
      containers:
        - name: spring-flyway-outside
          image: hanzhukruslan/spring-flyway-outside:1
          ports:
            - containerPort: 8888